/**
 * What: every source used to brief a card, in one list.
 * Why: the Receipts page is a delivery, not a footer. If we used it, it lives here.
 */

export type ReceiptKind = "primary" | "timeline" | "news" | "investigation" | "reference";

export interface Receipt {
  readonly id: string;
  readonly title: string;
  readonly publisher: string;
  readonly url: string;
  readonly kind: ReceiptKind;
  readonly usedFor: readonly string[];
  readonly note: string;
  readonly truth: "LT" | "IT" | "DK" | "mixed";
}

export const RECEIPTS: readonly Receipt[] = [
  {
    id: "cfr-timeline",
    title: "U.S. Relations With Iran, 1953–2025",
    publisher: "Council on Foreign Relations",
    url: "https://www.cfr.org/timelines/us-relations-iran-1953-2025",
    kind: "timeline",
    usedFor: ["rail", "atoms-1957", "iran-iraq-1980", "impeached-1981", "seated-1981", "iran-contra-1985", "cup-1988", "natanz-2002", "late"],
    note: "Spine dates. Treat as a chronology, not a verdict on motives.",
    truth: "LT",
  },
  {
    id: "alj-2025",
    title: "History of US-Iran relations, from the 1953 regime change to Trump strikes",
    publisher: "Al Jazeera",
    url: "https://www.aljazeera.com/news/2025/6/23/history-of-us-iran-relations-from-the-1953-regime-change-to-trump-strikes",
    kind: "news",
    usedFor: ["coup-1953", "soleimani-2020", "rail"],
    note: "Used for the public memory of 1953 and later kinetic shots. Not the CIA file.",
    truth: "mixed",
  },
  {
    id: "cia-1953",
    title: "CIA acknowledges role in 1953 Iran coup",
    publisher: "National Security Archive / CIA FOIA",
    url: "https://nsarchive.gwu.edu/briefing-book/iran/2013-08-19/cia-confirms-role-1953-iranian-coup",
    kind: "primary",
    usedFor: ["coup-1953"],
    note: "LT on US/UK involvement. The Agency admitted it decades later. Tudeh is the file they sold. A file is not a proof.",
    truth: "LT",
  },
  {
    id: "nyt-shah-cancer",
    title: "Shah's cancer is diagnosed and cure potential exists",
    publisher: "The New York Times",
    url: "https://www.nytimes.com/1979/10/26/archives/shahs-cancer-is-diagnosed-and-cure-potential-exists-took-diagnosis.html",
    kind: "news",
    usedFor: ["revolution-1979"],
    note: "Histiocytic lymphoma diagnosed in New York. Carter's admission of the Shah is the spark the occupiers used.",
    truth: "LT",
  },
  {
    id: "nasr-roads",
    title: "Iran's Roads Not Taken",
    publisher: "Foreign Affairs (Vali Nasr)",
    url: "https://www.foreignaffairs.com/iran/irans-roads-not-taken-nasr",
    kind: "investigation",
    usedFor: ["natanz-2002"],
    note: "The 2003 Swiss fax is real. How serious the Supreme Leader was is DK-to-IT.",
    truth: "mixed",
  },
  {
    id: "stuxnet-wiki",
    title: "Operation Olympic Games / Stuxnet",
    publisher: "Wikipedia (index of cited reporting)",
    url: "https://en.wikipedia.org/wiki/Operation_Olympic_Games",
    kind: "reference",
    usedFor: ["stuxnet-2010"],
    note: "LT that Stuxnet hit Natanz. LT-to-IT on US-Israel authorship. Damage numbers are IT.",
    truth: "mixed",
  },
  {
    id: "ap-nuke-timeline",
    title: "Iran nuclear timeline",
    publisher: "Associated Press",
    url: "https://apnews.com/article/iran-us-nuclear-timeline-war-146b4072f1f6cc43cfd3bde740313a5c",
    kind: "timeline",
    usedFor: ["jcpoa-2015", "rail"],
    note: "Deal text is LT. Whether it blocked the bomb or paved a delayed path is the fight.",
    truth: "mixed",
  },
  {
    id: "bbc-white-wed",
    title: "White Wednesdays / compulsory hijab protests",
    publisher: "BBC",
    url: "https://www.bbc.co.uk/news/world-middle-east-40218711",
    kind: "news",
    usedFor: ["white-wednesdays-2017"],
    note: "Campaign and arrests happened. Do not collapse this into 2022.",
    truth: "LT",
  },
  {
    id: "nyt-archive-raid",
    title: "Mossad nuclear archive raid, southern Tehran",
    publisher: "The New York Times",
    url: "https://www.nytimes.com/2018/07/15/us/politics/iran-israel-mossad-nuclear.html",
    kind: "news",
    usedFor: ["archive-2018"],
    note: "LT on the raid and that the files show structured AMAD-era weaponization work. DK how much stayed live after 2003.",
    truth: "mixed",
  },
  {
    id: "ap-2019",
    title: "2019 tanker, drone, Abqaiq timeline",
    publisher: "Associated Press",
    url: "https://apnews.com/article/timeline-iran-election-nuclear-f3beadc54c44a9ff74989cbf45d9a270",
    kind: "timeline",
    usedFor: ["hormuz-2019"],
    note: "LT on the Global Hawk shootdown and tanker seizures. Abqaiq attribution is the official US/Saudi line.",
    truth: "mixed",
  },
  {
    id: "quds-day",
    title: "Quds Day",
    publisher: "Wikipedia (index)",
    url: "https://en.wikipedia.org/wiki/Quds_Day",
    kind: "reference",
    usedFor: ["revolution-1979", "factions"],
    note: "Khomeini made Quds Day official August 1979. Death to Israel is a founding slogan, not a late unlock.",
    truth: "LT",
  },
  {
    id: "ohchr-poison",
    title: "Deliberate poisoning of schoolgirls",
    publisher: "UN OHCHR",
    url: "https://www.ohchr.org/en/press-releases/2023/03/iran-deliberate-poisoning-schoolgirls-further-evidence-continuous-violence",
    kind: "investigation",
    usedFor: ["poisonings-2022"],
    note: "Early international figure used by UN special experts, March 2023: more than 1,200 schoolgirls. Who did it is DK.",
    truth: "mixed",
  },
  {
    id: "stanford-poison",
    title: "School poisonings in Iran: an open-source investigation",
    publisher: "Stanford Law",
    url: "https://law.stanford.edu/publications/school-poisonings-in-iran-an-open-source-investigation/",
    kind: "investigation",
    usedFor: ["poisonings-2022"],
    note: "2025 review of a subset: real physical symptoms, not 'just nerves'. State failed to investigate while arresting people for talking.",
    truth: "mixed",
  },
  {
    id: "wiki-iran-iraq-aid",
    title: "International aid to combatants in the Iran–Iraq War",
    publisher: "Wikipedia (index of cited figures)",
    url: "https://en.wikipedia.org/wiki/International_aid_to_combatants_in_the_Iran%E2%80%93Iraq_War",
    kind: "reference",
    usedFor: ["iran-iraq-1980"],
    note: "Gulf money and European dual supply. Exact dollar totals vary. The strategy (neither side wins) does not.",
    truth: "mixed",
  },
  {
    id: "eisenhower-afp",
    title: "Atoms for Peace",
    publisher: "Eisenhower Presidential Library / public record",
    url: "https://www.eisenhowerlibrary.gov/research/online-documents/atoms-peace",
    kind: "primary",
    usedFor: ["atoms-1957"],
    note: "US supplied the Tehran Research Reactor and fuel. Indigenous enrichment is a later argument, not the original deal.",
    truth: "LT",
  },
  {
    id: "white-rev-britannica",
    title: "White Revolution",
    publisher: "Encyclopaedia Britannica",
    url: "https://www.britannica.com/event/White-Revolution",
    kind: "reference",
    usedFor: ["white-revolution-1963"],
    note: "Land reform, literacy corps, women's suffrage, 1963 plebiscite. Clerical opposition and Khomeini's emergence are LT. How much land actually moved is argued.",
    truth: "mixed",
  },
  {
    id: "frus-kennedy-iran",
    title: "Iran Task Force / Amini reform pressure, 1961",
    publisher: "US State Department, Foreign Relations of the United States",
    url: "https://history.state.gov/historicaldocuments/frus1961-63v17/d50",
    kind: "primary",
    usedFor: ["white-revolution-1963"],
    note: "Kennedy's people treat Amini's reform cabinet as maybe the last chance. They want socio-economic reform over military baksheesh. LT on the cable. IT on whether it undercut the left.",
    truth: "LT",
  },
  {
    id: "nixon-twin-pillars",
    title: "Nixon, Kissinger, and the Shah: the 1972 Tehran arms agreement",
    publisher: "War on the Rocks / FRUS",
    url: "https://warontherocks.com/nixon-kissinger-and-the-shah-a-troika-of-realists/",
    kind: "investigation",
    usedFor: ["weapons-1972"],
    note: "May 1972 blank check: any conventional US weapons system, any quantity. Twin pillars under the Nixon Doctrine. Sales then jump. George Ball's liquor-store line is IT.",
    truth: "mixed",
  },
  {
    id: "family-protection",
    title: "Family law in modern Iran / Family Protection Law",
    publisher: "Encyclopaedia Iranica",
    url: "https://www.iranicaonline.org/articles/family-law-iii-in-modern-persia/",
    kind: "reference",
    usedFor: ["weapons-1972", "veil-1979"],
    note: "1967 law, 1975 expansion: courts, marriage age, polygamy squeezed. Khomeini denounced it in 1967. Repealed in the first weeks of 1979. LT.",
    truth: "LT",
  },
  {
    id: "iwd-1979",
    title: "International Women's Day protests, Tehran, 8 March 1979",
    publisher: "Wikipedia (index of cited reporting) / Iranica",
    url: "https://en.wikipedia.org/wiki/1979_International_Women%27s_Day_protests_in_Iran",
    kind: "reference",
    usedFor: ["veil-1979"],
    note: "Thousands of women protest compulsory hijab after Khomeini's ministry order. Temporary delay, then the law lands. Family Protection is already being treated as void. LT on the protests. IT on 'they marched with him.'",
    truth: "mixed",
  },
  {
    id: "nara-hostages",
    title: "444 Days: Selected Records Concerning the Iran Hostage Crisis 1979-1981",
    publisher: "US National Archives",
    url: "https://www.archives.gov/research/foreign-policy/iran-hostage-crisis",
    kind: "primary",
    usedFor: ["hostages-1979", "inaugurated-1981", "election-1980"],
    note: "LT on 4 November 1979 seizure, Shah admitted 22 October, 444 days, release 20 January 1981. 13 released in November 1979; Richard Queen in July 1980; 52 remained.",
    truth: "LT",
  },
  {
    id: "banisadr-impeach",
    title: "Abolhassan Banisadr",
    publisher: "Encyclopaedia Britannica",
    url: "https://www.britannica.com/biography/Abolhassan-Bani-Sadr",
    kind: "reference",
    usedFor: ["impeached-1981", "seated-1981"],
    note: "LT: impeached 21 June 1981, fled to France. Rajai assassinated 30 August 1981. Khamenei inaugurated president 13 October 1981. He is not yet the Leader.",
    truth: "LT",
  },
  {
    id: "frus-eagle-claw",
    title: "Eagle Claw / the failed rescue, 25 April 1980",
    publisher: "US State Department, Foreign Relations of the United States",
    url: "https://history.state.gov/historicaldocuments/frus1977-80v11p1/d269",
    kind: "primary",
    usedFor: ["hostages-1979"],
    note: "LT on the raid, the White House statement, Vance's resignation. Desert One is the strip. Eight dead.",
    truth: "LT",
  },
  {
    id: "beirut-1983",
    title: "Beirut barracks bombing, 23 October 1983",
    publisher: "CNN Fast Facts / US reporting",
    url: "https://www.cnn.com/world/middleeast/beirut-marine-barracks-bombing-fast-facts",
    kind: "reference",
    usedFor: ["lebanon-1983"],
    note: "LT: 241 US dead including 220 Marines, 58 French the same morning. Truck bomb 6:22 a.m. at the airport barracks. Marines withdraw February 1984. Later US court judgment: Hezbollah at Iranian direction. Attribution at the time was Islamic Jihad.",
    truth: "mixed",
  },
  {
    id: "iran-contra",
    title: "The Iran-Contra Affair, 1983-1988",
    publisher: "National Security Archive",
    url: "https://nsarchive.gwu.edu/project/iran-contra-affair",
    kind: "primary",
    usedFor: ["iran-contra-1985", "cup-1988"],
    note: "LT on the arms sales to Iran, the diversion to the Contras, Boland, the November 1986 exposure. Hostages for missiles is the trade. The profit walking to Nicaragua is the other half.",
    truth: "LT",
  },
  {
    id: "vincennes-1988",
    title: "Iran Air Flight 655 / USS Vincennes, 3 July 1988",
    publisher: "Wikipedia (index of cited reporting)",
    url: "https://en.wikipedia.org/wiki/Iran_Air_Flight_655",
    kind: "reference",
    usedFor: ["cup-1988"],
    note: "LT: 290 dead. Washington calls it a mistake. 18 July Iran accepts Resolution 598. Khomeini's cup of poison. Ceasefire 20 August 1988.",
    truth: "LT",
  },
];

export function receiptById(id: string): Receipt | undefined {
  return RECEIPTS.find((r) => r.id === id);
}

export function receiptsForCard(cardId: string): Receipt[] {
  return RECEIPTS.filter((r) => r.usedFor.includes(cardId) || r.usedFor.includes("rail"));
}
